#!/usr/bin/env bash
#
# Measure the binary footprint of a compiled Seq program against a bare
# Rust binary on the *current* platform, and record the result in
# docs/footprint-measurements.md.
#
# Why this exists: binary sizes vary significantly across OS/arch
# (notably, Linux embeds DWARF in the binary while macOS keeps it in a
# separate .dSYM bundle), so hand-quoted numbers in prose go stale and
# misrepresent platforms they were never measured on. This records real,
# reproducible numbers per platform.
#
# The report is idempotent per platform: re-running on a platform refreshes
# only that platform's section, leaving other platforms' sections intact.
# Run it on each platform you care about and commit the result.
#
# Sizes are reported in decimal units (1 KB = 1000 bytes) to match `ls`
# --si and common intuition, with the exact byte count alongside as the
# unambiguous source of truth.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

REPORT="docs/footprint-measurements.md"
SEQC="target/release/seqc"
EXAMPLE="examples/basics/hello-world.seq"

if [ ! -x "$SEQC" ]; then
    echo "error: $SEQC not found. Build it first (just build-compiler)." >&2
    exit 1
fi

bytes() { wc -c < "$1" | tr -d ' '; }
human() {
    awk -v b="$1" 'BEGIN {
        if (b >= 1000000) printf "%.2f MB", b / 1000000
        else printf "%.0f KB", b / 1000
    }'
}

PLATFORM="$(uname -s) $(uname -m)"
KEY="$(printf '%s' "$PLATFORM" | tr ' ' '-')"
RUSTC="$(rustc --version | awk '{print $2}')"
SEQC_VER="$("$SEQC" --version | awk '{print $NF}')"
DATE="$(date -u +%Y-%m-%d)"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "Measuring on $PLATFORM (rustc $RUSTC, seqc $SEQC_VER)..."

# --- Seq binary ---
SEQ_BIN="$WORK/hello-seq"
"$SEQC" build "$EXAMPLE" -o "$SEQ_BIN" >/dev/null
SEQ_DEFAULT=$(bytes "$SEQ_BIN")
cp "$SEQ_BIN" "$SEQ_BIN.stripped"
strip "$SEQ_BIN.stripped"
SEQ_STRIPPED=$(bytes "$SEQ_BIN.stripped")

# --- Bare Rust binary ---
# Two profiles: cargo's default release (opt-level 3, no LTO), and the
# same with LTO + codegen-units=1, which is exactly this repo's release
# profile (Cargo.toml [profile.release]) and the apples-to-apples
# comparison for the Seq binary above.
RHW="$WORK/rhw"
cargo new --bin "$RHW" >/dev/null 2>&1
( cd "$RHW" && cargo build --release >/dev/null 2>&1 )
RUST_DEFAULT=$(bytes "$RHW/target/release/rhw")

cat >> "$RHW/Cargo.toml" <<'PROFILE'

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
PROFILE
( cd "$RHW" && cargo build --release >/dev/null 2>&1 )
RUST_LTO=$(bytes "$RHW/target/release/rhw")
cp "$RHW/target/release/rhw" "$WORK/rhw.stripped"
strip "$WORK/rhw.stripped"
RUST_LTO_STRIPPED=$(bytes "$WORK/rhw.stripped")

OVERHEAD=$((SEQ_STRIPPED - RUST_LTO_STRIPPED))
EMBEDDED=$((SEQ_DEFAULT - SEQ_STRIPPED))

# --- Emit the per-platform block ---
BLOCK="$WORK/block.md"
BEGIN="<!-- BEGIN $KEY -->"
END="<!-- END $KEY -->"
{
    echo "$BEGIN"
    echo "### $PLATFORM"
    echo ""
    echo "_Measured $DATE · rustc $RUSTC · seqc ${SEQC_VER}_"
    echo ""
    echo "| Artifact | Size | Bytes |"
    echo "|---|---:|---:|"
    printf '| %s | %s | %s |\n' "\`seqc build\` hello-world (default)"            "$(human "$SEQ_DEFAULT")"       "$SEQ_DEFAULT"
    printf '| %s | %s | %s |\n' "\`seqc build\`, stripped"                        "$(human "$SEQ_STRIPPED")"      "$SEQ_STRIPPED"
    printf '| %s | %s | %s |\n' "bare Rust \`--release\` (opt-level 3)"           "$(human "$RUST_DEFAULT")"      "$RUST_DEFAULT"
    printf '| %s | %s | %s |\n' "bare Rust \`--release\` + LTO (Seq's profile)"   "$(human "$RUST_LTO")"          "$RUST_LTO"
    printf '| %s | %s | %s |\n' "bare Rust + LTO, stripped"                       "$(human "$RUST_LTO_STRIPPED")" "$RUST_LTO_STRIPPED"
    echo ""
    echo "- Runtime overhead (stripped Seq − stripped Rust): **$(human "$OVERHEAD")**"
    echo "- Debug info / symbols carried in the default binary (default − stripped): **$(human "$EMBEDDED")**"
    echo "$END"
} > "$BLOCK"

if [ -f "$REPORT" ] && grep -qF "$BEGIN" "$REPORT"; then
    # Replace this platform's existing block in place.
    awk -v begin="$BEGIN" -v end="$END" -v blockfile="$BLOCK" '
        $0 == begin { while ((getline line < blockfile) > 0) print line; skip = 1; next }
        $0 == end   { skip = 0; next }
        skip != 1   { print }
    ' "$REPORT" > "$WORK/report.md"
    mv "$WORK/report.md" "$REPORT"
else
    if [ ! -f "$REPORT" ]; then
        {
            echo "# Binary Footprint Measurements"
            echo ""
            echo "Generated by \`just footprint\` (scripts/measure-footprint.sh)."
            echo "One section per platform; re-running on a platform refreshes its"
            echo "section. Exact byte counts are the source of truth; the Size column"
            echo "is a decimal-unit (1 KB = 1000 bytes) convenience."
            echo ""
        } > "$REPORT"
    fi
    echo "" >> "$REPORT"
    cat "$BLOCK" >> "$REPORT"
fi

echo "Wrote $PLATFORM section to $REPORT"
