#!/usr/bin/env bash
#
# Measure the optimized, *stripped* production binary size of a hello-world
# program — for bare Rust, Seq, and Go — on the current platform, and record
# it as one row in docs/footprint-measurements.md.
#
# "Production size" = the artifact you actually ship: release-optimized with
# debug info stripped.
#   - Rust and Seq use this repo's [profile.release] (opt-level 3 + LTO +
#     codegen-units=1), then `strip`.
#   - Go uses `go build -ldflags="-s -w"`, its idiomatic minimal build.
# Go is included for perspective: it is another runtime-bearing language, so
# it anchors the upper end of "reasonable" for a self-contained binary.
#
# The much larger default `seqc build` output is almost entirely DWARF debug
# info (embedded in the binary on Linux, kept in a separate .dSYM bundle on
# macOS); it is stripped before shipping, so it is not what this records.
#
# Idempotent per platform: re-running refreshes only the current platform's
# row, leaving other platforms' rows intact. Run it on each platform you ship
# to and commit the result.
#
# Sizes use decimal units (1 KB = 1000 bytes) to match `ls --si`.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

REPORT="docs/footprint-measurements.md"
SEQC="target/release/seqc"
EXAMPLE="examples/basics/hello-world.seq"

if [ ! -x "$SEQC" ]; then
    echo "error: $SEQC not found. Build it first (just build-compiler)." >&2
    exit 1
fi

bytes() { wc -c < "$1" | tr -d ' '; }
human() {
    awk -v b="$1" 'BEGIN {
        if (b >= 1000000) printf "%.2f MB", b / 1000000
        else printf "%.0f KB", b / 1000
    }'
}

PLATFORM="$(uname -s) $(uname -m)"
RUSTC="$(rustc --version | awk '{print $2}')"
SEQC_VER="$("$SEQC" --version | awk '{print $NF}')"
DATE="$(date -u +%Y-%m-%d)"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "Measuring on $PLATFORM (rustc $RUSTC, seqc $SEQC_VER)..."

# Seq: build, strip, measure.
SEQ_BIN="$WORK/hello-seq"
"$SEQC" build "$EXAMPLE" -o "$SEQ_BIN" >/dev/null
strip "$SEQ_BIN"
SEQ=$(human "$(bytes "$SEQ_BIN")")

# Bare Rust: build with this repo's release profile, strip, measure.
RHW="$WORK/rhw"
cargo new --bin "$RHW" >/dev/null 2>&1
cat >> "$RHW/Cargo.toml" <<'PROFILE'

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
PROFILE
( cd "$RHW" && cargo build --release >/dev/null 2>&1 )
strip "$RHW/target/release/rhw"
RUST=$(human "$(bytes "$RHW/target/release/rhw")")

# Go: idiomatic minimal build (-s strips the symbol table, -w omits DWARF).
GO="—"
GO_TOOLCHAIN=""
if command -v go >/dev/null 2>&1; then
    GHW="$WORK/ghw"
    mkdir -p "$GHW"
    cat > "$GHW/main.go" <<'GO_SRC'
package main

import "fmt"

func main() {
	fmt.Println("Hello, World!")
}
GO_SRC
    ( cd "$GHW" && go mod init hello >/dev/null 2>&1 && go build -ldflags="-s -w" -o hello . >/dev/null 2>&1 )
    GO=$(human "$(bytes "$GHW/hello")")
    GO_TOOLCHAIN=" · go $(go version | awk '{print $3}' | sed 's/^go//')"
fi

ROW="| $PLATFORM | $RUST | $SEQ | $GO | $DATE · rustc $RUSTC · seqc $SEQC_VER$GO_TOOLCHAIN |"
PREFIX="| $PLATFORM |"

if [ ! -f "$REPORT" ]; then
    {
        echo "# Binary Footprint Measurements"
        echo ""
        echo "Optimized, **stripped** production binary size of a hello-world"
        echo "program — the artifact you actually ship. Rust and Seq are built"
        echo "with this repo's \`[profile.release]\` (opt-level 3 + LTO +"
        echo "codegen-units=1) then stripped; Go uses \`go build -ldflags=\"-s -w\"\`."
        echo "Go is shown for perspective as another runtime-bearing language."
        echo ""
        echo "The much larger default \`seqc build\` output is almost all DWARF"
        echo "debug info (embedded in the binary on Linux, a separate \`.dSYM\` on"
        echo "macOS) and is stripped before shipping, so it is not shown here."
        echo ""
        echo "Generated by \`just footprint\` (scripts/measure-footprint.sh); each"
        echo "platform's row is refreshed when you run the recipe on that platform."
        echo ""
        echo "<!-- ANCHOR: table -->"
        echo "| Platform | Rust | Seq | Go | Measured |"
        echo "|---|---:|---:|---:|---|"
        echo "$ROW"
        echo "<!-- ANCHOR_END: table -->"
        echo ""
        echo "\`—\` = not yet measured on that platform; run \`just footprint\` there."
    } > "$REPORT"
elif grep -qF "$PREFIX" "$REPORT"; then
    # Replace this platform's existing row in place.
    awk -v prefix="$PREFIX" -v row="$ROW" '
        index($0, prefix) == 1 { print row; next }
        { print }
    ' "$REPORT" > "$WORK/report.md"
    mv "$WORK/report.md" "$REPORT"
else
    # New platform: insert a row just before the closing table anchor.
    awk -v row="$ROW" '
        /<!-- ANCHOR_END: table -->/ { print row }
        { print }
    ' "$REPORT" > "$WORK/report.md"
    mv "$WORK/report.md" "$REPORT"
fi

echo "Updated $PLATFORM row in $REPORT"
